### ISSUE TITLE
Does not compile (several errors)

### ISSUE THREAD

**Issue by Polda18** [roukaour/spectrogram#1]
Hello. Due to lack of project files in your git, I had to import source files as new project, in order to be able to compile the source code into a working JAR file. However, several errors popped out when trying to compile the program. This is event log console output:
```
30. 6. 2018
15:31	IDE and Plugin Updates: IntelliJ IDEA is ready to update.

15:41	Compilation completed with 16 errors and 0 warnings in 45s 865ms
```

And this is brief preview of detailed errors:
![Compiler errors](https://preview.ibb.co/nN5FSJ/IDEAERR.jpg)

These errors are generally the same throughout the entire project, all because of missing library you're rependent on. Seems like that library isn't standard Java library to include and has to be installed. However, your README doesn't even mention anything about compiling the code, nor what library should I install before compiling the code. Would be worth of telling people, right?

**Comment by rcrath** [comment]
Has anyone got this to compile? A step by step from these files to  a working program would be great!

**Comment by rcrath** [comment]
I guess this is a bit of a lost cause as the dev has not been here in three years and the repo seven.
 I suppose I could fork it but, not a coder.

**Comment by Polda18** [comment]
Well, if anybody has some detective skills that would yield the correct library to include, I would be more than happy. Google didn't find anything useful tho.

**Comment by Polda18** [comment]
I think I'm gonna close this issue as not resolved, this is clearly an abandoned project and I don't think it is worth waiting for any response here. I would fork it, too, but this is kind of too technical for me. Not sure what to do with it and where to even begin. Sorry folks who had a hope of this code finishing. I'll keep it in my starred repos for future, but I don't promise anything about forking it and actually finishing the project for whoever abandoned it.
